Fix incompatibility with Haystack 2.5
AttributeError was raised at /search/advance/

'HaystackAdvanceSearch' object has no attribute 'context_class'

The context_instance parameter in render_to_response was deprecated in Django 1.8, and removed in Django 1.10.